# Generated by Django 4.1.5 on 2023-01-12 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=21)),
                ('status', models.CharField(choices=[('V', 'A venda'), ('C', 'Comprado')], max_length=1)),
                ('photo', models.ImageField(upload_to='fotos_livros')),
                ('genres', models.ManyToManyField(to='posts.genre')),
                ('tags', models.ManyToManyField(to='posts.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
