# Generated by Django 4.1.5 on 2023-02-09 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AG', 'Aguardando Aprovação'), ('AP', 'Aprovado'), ('RE', 'Recusado')], default='AG', max_length=2)),
                ('data', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
